server:
  port: 0 # Assign a random port

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: khanh090203
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      defaultBinder: rabbit
      binders:
        rabbit:
          type: rabbit
      bindings:
        # This defines an output channel named 'userInvited-out-0'
        userInvited-out-0:
          binder: rabbit
          destination: user.invited
        userRegistered-out-0:
          binder: rabbit
          destination: user.registered
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope:
              - user:email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "7zZFJQIluiTVIZLWJzzEB8Qsd2oWWMCTlvp5WWMffStMaX-Biw04q3pox8z2Fx4BYSQr4MPRZejC-OAj2rsZHg"
    expiration-ms: 86400000 # 24 hours
  oauth:
    github:
      redirect-uri: ${GITHUB_REDIRECT_URI:recruitment-platform://auth/callback}
      authorize-redirect-uri: ${GITHUB_AUTHORIZE_REDIRECT_URI:http://localhost:8080/api/auth/oauth/github/callback}
