server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Disable automatic routing to prevent exposing internal APIs
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/** # Only public auth APIs are routed
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/companies/**
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**
        - id: user-profile-service
          uri: lb://USER-PROFILE-SERVICE
          predicates:
            - Path=/api/profiles/**
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/api/applications/**
        - id: interview-service
          uri: lb://INTERVIEW-SERVICE
          predicates:
            - Path=/api/interviews/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "# IMPORTANT: Must be the same as in auth-service"
