export const ROUTES = {
  home: "/",
  jobs: "/jobs",
  candidatePortal: "/candidate",
  candidateApplications: "/candidate/applications",
  candidateProfile: "/candidate/profile",
  candidateChat: "/candidate/chat",
  recruiterDashboard: "/dashboard",
  superAdminDashboard: "/dashboard/super-admin",
  superAdminCompanies: "/dashboard/super-admin/companies",
  superAdminUsers: "/dashboard/super-admin/users",
  companyAdminDashboard: "/dashboard/company",
  docs: "/docs",
  signIn: "/auth/sign-in",
  register: "/auth/register",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  acceptInvite: "/auth/accept-invite",
};
