server:
  port: 0 # Random port

spring:
  application:
    name: APPLICATION-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/application_db
    username: postgres
    password: khanh090203
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "7zZFJQIluiTVIZLWJzzEB8Qsd2oWWMCTlvp5WWMffStMaX-Biw04q3pox8z2Fx4BYSQr4MPRZejC-OAj2rsZHg"

security:
  oauth2:
    resourceserver:
      jwt:
        # IMPORTANT: Uncomment and provide a valid issuer-uri or jwk-set-uri
        # issuer-uri: http://localhost:8080/api/auth # Placeholder
        # jwk-set-uri: http://localhost:8080/api/auth/jwks
