server:
  port: 0 # Random port

spring:
  application:
    name: INTERVIEW-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/interview_db
    username: postgres
    password: khanh090203
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/api/auth # Placeholder
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      defaultBinder: rabbit
      binders:
        rabbit:
          type: rabbit
      bindings:
        interviewScheduled-out-0:
          binder: rabbit
          destination: interview.scheduled
        interviewRescheduled-out-0:
          binder: rabbit
          destination: interview.rescheduled

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "7zZFJQIluiTVIZLWJzzEB8Qsd2oWWMCTlvp5WWMffStMaX-Biw04q3pox8z2Fx4BYSQr4MPRZejC-OAj2rsZHg"
