apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: recruitment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: asia-southeast1-docker.pkg.dev/glass-respect-478307-a3/nqk/discovery-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8761"
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: recruitment
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
