apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: recruitment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-southeast1-docker.pkg.dev/glass-respect-478307-a3/nqk/frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: NEXT_PUBLIC_API_BASE_URL
            - name: NEXT_SERVER_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: NEXT_SERVER_API_BASE_URL
            - name: ACCESS_TOKEN_COOKIE_SECURE
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: ACCESS_TOKEN_COOKIE_SECURE
            - name: SITE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: FRONTEND_BASE_URL
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: recruitment
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
