apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: recruitment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: asia-southeast1-docker.pkg.dev/glass-respect-478307-a3/nqk/job-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: APP_JWT_SECRET
            - name: SUPABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: SUPABASE_HOST
            - name: SUPABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: SUPABASE_PORT
            - name: SUPABASE_DB
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: SUPABASE_DB
            - name: SUPABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: SUPABASE_USERNAME
            - name: SUPABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: SUPABASE_PASSWORD
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: recruitment
spec:
  selector:
    app: job-service
  ports:
    - port: 8080
      targetPort: 8080
