apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: recruitment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: asia-southeast1-docker.pkg.dev/glass-respect-478307-a3/nqk/notification-service:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: SPRING_RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: SPRING_RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: SPRING_RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: SPRING_RABBITMQ_PASSWORD
            - name: FRONTEND_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: recruitment-config
                  key: FRONTEND_BASE_URL
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: MAIL_PORT
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recruitment-secrets
                  key: MAIL_PASSWORD
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: recruitment
spec:
  selector:
    app: notification-service
  ports:
    - port: 8080
      targetPort: 8080
