apiVersion: v1
kind: ConfigMap
metadata:
  name: recruitment-config
  namespace: recruitment
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
  GATEWAY_BASE_URL: http://gateway-service:8080
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  CV_FONT_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
  NEXT_PUBLIC_API_BASE_URL: http://34.126.129.31:8080
